### ISSUE TITLE
Broken demo link

### ISSUE THREAD

**Issue by StephanAkkerman** [zouharvi/pwesuite#9]
In the readme, the following link does not work anymore.
>  For a demo, see [this Jupyter notebook](https://github.com/zouharvi/pwesuite/blob/master/meta/demo.ipynb).

It should be replaced with this URL: https://github.com/zouharvi/pwesuite/blob/master/demo.ipynb

**Comment by zouharvi** [comment]
Hi, sorry for having missed your issues, I didn't get a notification before. :slightly_smiling_face: 

You're right, fixed now.
